### ISSUE TITLE
Unexpected token '.' on v4

### ISSUE THREAD

**Issue by savingprivatebryan** [acacode/swagger-typescript-api#111]
Hi, when running v4 with the following params I am getting an error. Running on node v12.18.3. I can include the swagger definition if needed.

swagger-typescript-api -p "url" -o ./src/api -n file.ts

\node_modules\swagger-typescript-api\src\routes.js:415
          tags?.length && ` * @tags ${tags.join(", ")}`,
               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Code\SBIR_TeacherPortal\node_modules\swagger-typescript-api\src\index.js:12:38)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

**Comment by js2me** [comment]
Hello @savingprivatebryan , thanks for this issue, will fix that through 1 hour!

**Comment by js2me** [comment]
@savingprivatebryan should be fixed in 4.0.2!   
If you've got the same problem, please reopen issue!
