### ISSUE TITLE
Invalid character in header content ["transformRequest"] when using an axios client

### ISSUE THREAD

**Issue by kamzcgcg** [acacode/swagger-typescript-api#201]
I'm trying to use the generated axios client. I'm getting the following error:

```
    TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["transformRequest"]
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:241:14)
    at Object.request (http.js:46:10)
    at RedirectableRequest._performRequest (/Users/kamz/workspace/clarity/clarity-model/node_modules/follow-redirects/index.js:262:24)
    at new RedirectableRequest (/Users/kamz/workspace/clarity/clarity-model/node_modules/follow-redirects/index.js:60:8)
    at Object.request (/Users/kamz/workspace/clarity/clarity-model/node_modules/follow-redirects/index.js:458:14)
    at dispatchHttpRequest (/Users/kamz/workspace/clarity/clarity-model/node_modules/axios/lib/adapters/http.js:195:25)
    at new Promise (<anonymous>)
    at httpAdapter (/Users/kamz/workspace/clarity/clarity-model/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/Users/kamz/workspace/clarity/clarity-model/node_modules/axios/lib/core/dispatchRequest.js:52:10) {
  code: 'ERR_INVALID_CHAR'
}
```

Here's the code.

```
import { Api } from './Api' // generated API

(async () => {
  try {
    const client = new Api();
    await client.manager.getX({xId: '66666'});
  } catch (e) {
    console.log(e);
  }
})();

```

When I log requestParms I see this:

`"transformRequest":[null],"transformResponse":[null]`

When I add the following part of the request param:

`transformRequest: [(data, headers) => { return data; }]`

The error changes to become:

`UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["adapter"]
`

Note that I get this error regardless if my server is running or not.

**Comment by kamzcgcg** [comment]
I was able to debug this further. My investigation led me to a potential bug. Closing this issue and re-opening a different one.
