### ISSUE TITLE
Bad request (400) error when trying to retrieve Swagger json by URL behind corporate proxy

### ISSUE THREAD

**Issue by kel666** [acacode/swagger-typescript-api#234]
If I run swagger-typescript-api I get this error:

```
✨   try to get swagger by url "https://localhost:44368/swagger/v1/swagger.json"
(node:5904) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (C:\Users\C331663\source\repos\commodity-ui\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\C331663\source\repos\commodity-ui\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\C331663\source\repos\commodity-ui\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting
a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/a
pi/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a
 non-zero exit code.
```

First problem is that the Axios get for URL doesn't have a catch clause, so we have this awful dump.
Second problem is that I received a HTTP 400. After some investigation I found out was the corporate proxy which I'm behind.

I raised a PR to fix both problems:
https://github.com/acacode/swagger-typescript-api/pull/232

Would be thankful if you'd include it in next release.
Tnx
Fabio

**Comment by js2me** [comment]
Thank you @kel666 for your contribution!

**Comment by js2me** [comment]
If someone occurred with this problem reopen this issue please
