### ISSUE TITLE
Unexpected token '.' in swagger-typescript-api@9.3.1

### ISSUE THREAD

**Issue by IhnatKlimchuk** [acacode/swagger-typescript-api#313]
Steps to reproduce:
> npm i swagger-typescript-api -g
+ swagger-typescript-api@9.3.1

>npx swagger-typescript-api -p .\swagger.json  -o ./src/app/api -n client.ts

```
C:\work\notidar-web\node_modules\swagger-typescript-api\src\index.js:164
                if(schema.rawTypeData?.properties) {
                                      ^

SyntaxError: Unexpected token '.'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:986:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\work\notidar-web\node_modules\←[4mswagger-typescript-api←[24m\index.js:11:25)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
```

**Comment by mdavis95** [comment]
Install a newer nodejs version

**Comment by jeking3** [comment]
GitHub Actions run on node 12, so not supporting it until EOL in April 2022 kinda sucks.

**Comment by hedgepigdaniel** [comment]
it works on node 14 aswell, but is it really important to use this syntax? I work on a huge monorepo where it isn't so easy for me to update the node version.

If you want to use modern syntax, what about introducing a build step (Babel/esbuild/Typescript etc)? That way you can use whatever syntax without breaking compatibility.

And if not, then at least the `"engines"` field should be set in the `package.json` to indicate that node 14+ is required for the package to work.
