### ISSUE TITLE
TypeError: host.fileExists is not a function. When trying to generate types from swagger schema

### ISSUE THREAD

**Issue by antonmazhuto** [acacode/swagger-typescript-api#424]
I have .sh script 
`#!/usr/bin/env bash

# Generate types
sta -p http://localhost:4000/api-json -o ./src/types -n api.ts --responses --extract-request-params --no-client

# Remove eslint disabling rules
sed -E '/tslint:disable|eslint-disable/d' src/types/api.ts > src/types/api.out
mv src/types/api.out src/types/api.ts

# Run eslint
eslint --fix --no-ignore src/types/api.ts

# Run prettier
prettier --write src/types/api.ts

`

Then I tying to run `"api:update": "scripts/api.update.sh"` from my package.json
But getting such problem:
`/Users/antonmazuto/.nvm/versions/node/v16.16.0/bin/node /Users/antonmazuto/.yarn/bin/yarn.js run api:update
yarn run v1.22.19
warning ../../../../../package.json: No license field
$ scripts/api.update.sh
✨   try to get swagger by URL "http://localhost:4000/api-json"
✨   try to read templates from directory "/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/templates/default"
☄️    start generating your typescript api
TypeError: host.fileExists is not a function
    at Object.fileExists (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:167620:63)
    at Object.host.fileExists (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:117500:47)
    at getPackageJsonInfo (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:44461:37)
    at loadModuleFromSpecificNodeModulesDirectory (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:45001:27)
    at loadModuleFromImmediateNodeModulesDirectory (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:44982:58)
    at /Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:44972:39
    at Object.forEachAncestorDirectory (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:8370:26)
    at loadModuleFromNearestNodeModulesDirectoryWorker (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:44966:19)
    at loadModuleFromNearestNodeModulesDirectory (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:44958:16)
    at tryResolve (/Users/antonmazuto/Documents/my/my-apps/chat/chat-frontend-vite/node_modules/swagger-typescript-api/node_modules/typescript/lib/typescript.js:44053:34)
src/types/api.ts 235ms
✨  Done in 5.46s.

Process finished with exit code 0
`

**Comment by js2me** [comment]
Hi @antonmazhuto , which version of NodeJS and NPM do you use ?

**Comment by antonmazhuto** [comment]
Hi @js2me . I'm using node v16.16.0 and npm 8.11.0

**Comment by js2me** [comment]
@antonmazhuto version of swagger-typescript-api ?

**Comment by js2me** [comment]
@antonmazhuto I know about this problem but I fixed that in 10.0.2 version

**Comment by donysukardi** [comment]
Upgrading typescript seems to fix the issue for us.. Didn't have time to dig what was actually happening though 🤔

**Comment by antonmazhuto** [comment]
@js2me Thank you very much. I solved the problem by updating to the latest version of swagger-typescript-api
