### ISSUE TITLE
Error on generation

### ISSUE THREAD

**Issue by 1Lua** [acacode/swagger-typescript-api#603]
Whats wrong?
https://openapi.wildberries.ru/swagger.yaml - scheme
 
Command:
 ```
npx swagger-typescript-api -p https://openapi.wildberries.ru/swagger.yaml -o ./src -n api.ts -t ./api-template
 ```
Result:
```
npx swagger-typescript-api -p https://openapi.wildberries.ru/swagger.yaml -o ./src -n api.ts -t ./api-template
✨   swagger-typescript-api(13.0.3),npm/9.8.1 node/v16.16.0 linux x64 workspaces/false,debug mode DISABLED
✨   try to read templates from directory "/home/matvey/Desktop/wb-test/api-template"
✨   "api" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "data contracts" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "data contract js doc" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "interface data contract" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "type data contract" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "enum data contract" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "object field js doc" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "http client" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "route types" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   "route name" template found in "/home/matvey/Desktop/wb-test/api-template"
✨   try to get swagger by URL "https://openapi.wildberries.ru/swagger.yaml"
⭐   start generating your typescript api
❗   Module "public" already has method "serversPublic()" 
❗   This method has been renamed to "serversPublic2()" to solve conflict names.
❗   Module "public" already has method "serversPublic()" 
❗   This method has been renamed to "serversPublic3()" to solve conflict names.
❗   Module "public" already has method "serversPublic()" 
❗   This method has been renamed to "serversPublic4()" to solve conflict names.
❗   Module "public" already has method "serversPublic()" 
❗   This method has been renamed to "serversPublic5()" to solve conflict names.
❗   Module "public" already has method "serversPublic()" 
❗   This method has been renamed to "serversPublic6()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent2()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent3()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent4()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent5()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent6()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent7()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent8()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent9()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent10()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent11()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent12()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent13()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent14()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent15()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent16()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent17()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent18()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent19()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent20()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent21()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent22()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent23()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent24()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent25()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent26()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent27()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent28()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent29()" to solve conflict names.
❗   Module "content" already has method "serversContent()" 
❗   This method has been renamed to "serversContent30()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi2()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi3()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi4()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi5()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi6()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi7()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi8()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi9()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi10()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi11()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi12()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi13()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi14()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi15()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi16()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi17()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi18()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi19()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi20()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi21()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi22()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi23()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi24()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi25()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi26()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi27()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi28()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi29()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi30()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi31()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi32()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv2()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv3()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv4()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv5()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv6()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv7()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv8()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv9()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv10()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv11()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv12()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv13()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv14()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv15()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv16()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv17()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv18()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv19()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv20()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv21()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv22()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv23()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv24()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv25()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv26()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv27()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv28()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv29()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv30()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv31()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv32()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv33()" to solve conflict names.
❗   Module "adv" already has method "serversAdv()" 
❗   This method has been renamed to "serversAdv34()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi33()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi34()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi35()" to solve conflict names.
❗   Module "api" already has method "serversApi()" 
❗   This method has been renamed to "serversApi36()" to solve conflict names.
TypeError: Cannot read properties of null (reading 'x-omitempty')
    at SchemaUtils.isPropertyRequired (/home/matvey/Desktop/wb-test/node_modules/swagger-typescript-api/src/schema-parser/schema-utils.js:55:23)
    at /home/matvey/Desktop/wb-test/node_modules/swagger-typescript-api/src/schema-parser/base-schema-parsers/object.js:32:41
    at /home/matvey/Desktop/wb-test/node_modules/lodash/lodash.js:3585:27
    at /home/matvey/Desktop/wb-test/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/matvey/Desktop/wb-test/node_modules/lodash/lodash.js:3032:24)
    at /home/matvey/Desktop/wb-test/node_modules/lodash/lodash.js:4936:18
    at baseMap (/home/matvey/Desktop/wb-test/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/home/matvey/Desktop/wb-test/node_modules/lodash/lodash.js:9622:14)
    at ObjectSchemaParser.getObjectSchemaContent (/home/matvey/Desktop/wb-test/node_modules/swagger-typescript-api/src/schema-parser/base-schema-parsers/object.js:31:33)
    at ObjectSchemaParser.parse (/home/matvey/Desktop/wb-test/node_modules/swagger-typescript-api/src/schema-parser/base-schema-parsers/object.js:7:36)
```

**Comment by GMaiolo** [comment]
@1Lua Were you able to solve this? I just encountered the same issue

**Comment by Deer403** [comment]
I just encountered the same issue @1Lua
